name: CI Build

on: [ push, pull_request ]

jobs:
    build:
        name: Build (JDK ${{ matrix.java }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [ '17', '18' ]

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Set up JDK ${{ matrix.java }}
                uses: actions/setup-java@v3
                with:
                    java-version: ${{ matrix.java }}
                    distribution: 'adopt'
                    cache: 'maven'

            -   name: Set up Etcd
                run: |
                    sudo apt -y install etcd
                    etcdctl set "cfg/string" "Hello World"
                    etcdctl set "cfg/integer" "1"
                    etcdctl set "cfg/intlist" "[1,2,3,4,5]"
                    etcdctl set "cfg/boolean" "true"
                    etcdctl set "cfg/file.test" "<FILE>./test;SGVsbG8gV29ybGQh"
                    echo -e "insecurepassword" | etcdctl user add root
                    etcdctl auth enable

            -   name: Set up Redis
                run: |
                    sudo apt -y install redis-server

            -   name: Build with Maven
                run: mvn --batch-mode --update-snapshots -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn test
