name: CI Build and Publish

on: [ push ]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'

            -   name: Build with Maven
                run: mvn --batch-mode --update-snapshots -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn test


    publish-ossrh:
        name: Publish to Central Repository
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')

        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'
                    server-id: ossrh
                    server-username: MAVEN_USERNAME
                    server-password: MAVEN_PASSWORD

            -   name: Install GPG secret key
                run: |
                    cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
                    gpg --list-secret-keys --keyid-format LONG

            -   name: Build and Publish
                env:
                    MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                    MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
                run: mvn --batch-mode --update-snapshots -DskipTests --no-transfer-progress -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -P sign-jars deploy
